name: Add a comment

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: set pr number
        run: echo "trabajnaod en algo "
      - uses: everphone-gmbh/github-asana-action@385529c13a4c0d311ac611ef4049f5a6ccf1048e
        with:
          asana-pat: ${{ secrets.ASANA_TOKEN }}
          action: 'add-comment'
          comment-id: "#pr:1"
          text: 'Estamos agregand un comentario desde un action'
          is-pinned: true
